### ISSUE TITLE
Implement volume presets for each channel

### ISSUE THREAD

**Issue by PwnicornDev** [sixtyeight/slackomatic#1]
For example the Wii is much louder than most YouTube videos, so we have to manually adjust the volume on the Yamaha everytime we switch from/to the Wii. A sane default for the Wii would be -35db, while 30-ish is better for the ScreenInvader because it has software volume controls.
If the Yamaha doesn't support setting a numeric value, we could turn the volume all the way down and then x steps up.

**Comment by sixtyeight** [comment]
E_WONT_FIX
